blogapp/urls.py
from django.urls import path, re_path
from .views import *


app_name = 'blog_app'


urlpatterns = [
    path('blog_create/', BlogCreate.as_view(), name='blog_create'),
    path('blog_detail/<int:pk>/', blog_detail, name='blog_detail'),
    path('blog_update/<int:pk>/', BlogUpdate.as_view(), name='blog_update'),
    path('blog_delete/<int:pk>/', BlogDelete.as_view(), name='blog_delete'),

    path('entry_create/<int:pk>/', EntryCreate.as_view(), name='entry_create'),
    path('entry_detail/<int:pk>/', entry_detail, name='entry_detail'),
    path('entry_update/<int:pk>/', EntryUpdate.as_view(), name='entry_update'),

    path('by_tematics/<int:pk>/', BlogByTematicsListView.as_view(), name='by_tematics'),

    path('by_owner/<int:pk>/', BlogByOwnerListView.as_view(), name='by_owner'),

    path('block_entry_create/<int:pk>/', BlockEntryCreate.as_view(), name='block_entry_create'),
    path('block_update/<int:entry_pk>/<int:pk>/', BlockEntryUpdate.as_view(), name='block_update'),
    path('block_delete/<int:entry_pk>/<int:pk>/', BlockDelete.as_view(), name='block_delete'),

]

blogsite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from mainapp.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cabinet/', include('cabinet.urls')),
    url(r'^$', index, name='index'),
    path('main/', include('mainapp.urls')),
    path('blog/', include('blogapp.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from .views import *


app_name = 'mainapp'


urlpatterns = [
    url(r'^$', index, name='index'),
    path('send_message/<int:pk>/', send_message, name='send_message'),

    path('ajax/reload_group/', views.reload_group, name='ajax_reload_group'),  # скролл на странице index

    # панель вверху (раньше была слева)
    path('ajax/reload_data_left_bar/', views.reload_data_left_bar, name='ajax_reload_data_left_bar'),

    # страница комментариев
    path('ajax/reload_comment_block/<int:pk>/', reload_comment_block, name='ajax_reload_comment-block'),

    path('site-info/', site_info, name='site_info'),
    path('contacts/', contacts, name='contacts'),
]

mainapp/models.py
from django.db import models

# Create your models here.

mainapp/forms.py
from django import forms


class SendMessage(forms.Form):
    text_data = forms.CharField(label='Сообщение', widget=forms.Textarea)

mainapp/views.py
from django.shortcuts import render
from blogapp.forms import SearchBlog
from blogapp.models import Tematics, Blog, Entry, Comment, Answer
from cabinet.models import AdvUser
from django.core.paginator import Paginator
from .forms import SendMessage
from django.template.loader import render_to_string


def popup_and_last():
    populated = []
    arr_populated = Entry.objects.all().order_by('-count')
    count_pop = len(arr_populated)
    if count_pop <= 10:
        count_pop_max = count_pop
    else:
        count_pop_max = 10
    for i in range(count_pop_max):
        populated.append(arr_populated[i])

    last_entrys = []
    arr_populated = Entry.objects.all().order_by('-created')
    count_pop = len(arr_populated)
    if count_pop <= 10:
        count_pop_max = count_pop
    else:
        count_pop_max = 10
    for i in range(count_pop_max):
        last_entrys.append(arr_populated[i])

    return populated, last_entrys


def index(request, pk=None):
    title_name = 'Мой блог'
    description = "Мой блог: создай свой блог, делись мыслями и интересными историями."
    visible_blogs = Blog.objects.filter(visible='open').order_by('name')

    users_count = AdvUser.objects.all().count()  # счетчик всех пользователей
    blogs_count = Blog.objects.all().count()  # счетчик всех блогов
    all_know = Tematics.objects.all()  # все темы блогов

    paginator = Paginator(visible_blogs, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    populated, last_entrys = popup_and_last()

    arr = []
    if request.user.is_authenticated:
        blogs = Blog.objects.filter(owner=request.user).order_by('name')
        entrys = Entry.objects.filter(blog_id=pk).count()
        """ Ниже формируем массив для вывода вспомогательных данных в шаблон,
                поскольку требуется вывод сложных структур
            """

        for item_blog in blogs:
            count_entrys = Entry.objects.filter(blog_id=item_blog.pk).count()   # считаем количество сообщений блога
            item_value = {
                'pk': item_blog.pk,  # делаем привязку к блогу
                'value': count_entrys   # указываем количество сообщений блога
            }
            arr.append(item_value)
    else:
        blogs = []

    if request.method == 'POST':
        form = SearchBlog(request.POST)
        if form.is_valid():
            keydata = form.cleaned_data['keydata']
            current_blogs = Blog.objects.filter(name__icontains=keydata).order_by('name')

            paginator = Paginator(current_blogs, 10)
            page_number = request.GET.get('page')
            page_obj = paginator.get_page(page_number)

            context = {'page_obj': page_obj,
                       'users_count': users_count,
                       'blogs_count': blogs_count,
                       'all_know': all_know,
                       'keydata': keydata,
                       'serch_word': keydata
                       }
            return render(request, 'search_blog.html', context)
        else:
            context = {'form': form, }
            return render(request, 'index.html', context)
    else:
        form = SearchBlog()

        context = {'set_title': title_name,
                   'description': description,
                   'form': form,
                   'blogs': blogs,
                   'open_blogs': visible_blogs,
                   'arr': arr,   # передаем свои дополнительные данные
                   'page_obj': page_obj,
                   'users_count': users_count,
                   'blogs_count': blogs_count,
                   'all_know': all_know,
                   'populated': populated,
                   'last_entrys': last_entrys
                   }
        return render(request, 'index.html', context)


def reload_group(request):
    area_id = request.GET.get('id_area')
    current_group = Tematics.objects.filter(area_kn=area_id).order_by('name')
    return render(request, 'inc_templates_misc/group_dropdown_list_options.html', {'group_kn': current_group})


def reload_data_left_bar(request):
    """Здесь динамически выводим актуальные данные на странице в блок слева, обновляем 1 раз в 5 сек"""
    users_count =AdvUser.objects.all().count()     # счетчик всех пользователей
    blogs_count = Blog.objects.all().count()     # счетчик всех блогов
    all_know = Tematics.objects.all()     # все темы блогов
    comment_flag = False
    if request.user.is_authenticated:
        blogs = Blog.objects.filter(owner=request.user).order_by('name')
        arr = []
        for item_blog in blogs:
            # считаем количество сообщений блога
            count_entrys = Entry.objects.filter(blog_id=item_blog.pk).count()

            # считаем количество новых комментариев
            new_comments = Comment.objects.filter(entry_id__blog_id=item_blog.pk, new=True).count()
            if new_comments:
                comment_flag = True
            item_value = {
                'pk': item_blog.pk,  # делаем привязку к блогу
                'value': count_entrys,   # указываем количество сообщений блога
                'new_comments': new_comments,
                'visible': item_blog.visible,
            }
            arr.append(item_value)
        context = {
            'is_authenticated': True,
            'username': request.user.username,
            'blogs_count': blogs_count,
            'users_count': users_count,
            'users_blogs': Blog.objects.filter(owner=request.user).count(),
            'blogs': blogs,
            'arr': arr,
            'all_know': all_know,
            'comment_flag': comment_flag
        }
    else:
        context = {
            'is_authenticated': False,
            'blogs_count': blogs_count,
            'users_count': users_count,
            'all_know': all_know,
        }

    return render(request, 'inc_templates_misc/reload_data_left_bar.html', {'context': context})


def reload_comment_block(request, pk):
    current_comments = Comment.objects.filter(entry_id=pk).order_by('created')
    current_user = request.user
    current_entry = Entry.objects.get(pk=pk)    # получили сообщение
    current_comments_count = current_comments.count()
    array = []  # пустой массив для данных

    for comment in current_comments:
        current_item_answer = Answer.objects.filter(comment_id=comment.pk)
        item_value = {
            'pk': comment.pk,
            'value': current_item_answer
        }
        array.append(item_value)

    owner_entry = current_entry.owner
    if current_user == owner_entry:
        # обнуляем признак "new" только если смотрит хозяин сообщения
        show_new = True
        owner = True
        new_comments = Comment.objects.filter(entry_id=pk, new=True,).order_by('created')
        if new_comments:
            first_comment = new_comments[0]
            first_comment.new = False
            first_comment.save()

    else:
        show_new = False
        owner = False

    context = {
        'current_comments': current_comments,
        'current_comments_count': current_comments_count,
        'show_new': show_new,
        'owner': owner,     # хозяин / гость блога
        'array': array,
    }
    return render(request, 'inc_templates_misc/reload_comment_block.html', {'context': context})


def send_message(request, pk):
    users_count = AdvUser.objects.all().count()  # счетчик всех пользователей
    blogs_count = Blog.objects.all().count()  # счетчик всех блогов
    all_know = Tematics.objects.all()  # все темы блогов
    populated, last_entrys = popup_and_last()

    if request.method == 'POST':
        send_form = SendMessage(request.POST)
        if send_form.is_valid():
            text_data = send_form.cleaned_data['text_data']
            author = AdvUser.objects.get(pk=pk)

            moderators = AdvUser.objects.filter(is_staff=True)
            for moderator in moderators:
                context = {'moderator': moderator, 'text_data': text_data, 'author': author}
                subject = render_to_string('email/new_messages_letter.txt', context)
                body_text = render_to_string('email/new_messages_body.txt', context)
                moderator.email_user(subject, body_text)
            context = {
                'title_name': 'Создание сообщения',
                'description': "Создание сообщения",
                'send_form': send_form,
                'users_count': users_count,
                'blogs_count': blogs_count,
                'all_know': all_know,
                'populated': populated,
                'last_entrys': last_entrys
            }
            return render(request, 'messages_letter_succes.html', context)
        else:
            context = {'send_form': send_form, }
            return render(request, 'index.html', context)

    else:
        send_form = SendMessage()
        context = {
            'title_name': 'Создание сообщения',
            'description': "Создание сообщения",
            'send_form': send_form,
            'users_count': users_count,
            'blogs_count': blogs_count,
            'all_know': all_know,
            'populated': populated,
            'last_entrys': last_entrys
        }
        return render(request, 'send_message.html', context)


def site_info(request):
    if request.user.is_authenticated:
        blogs = Blog.objects.filter(owner=request.user).order_by('name')
    else:
        blogs = []

    users_count = AdvUser.objects.all().count()  # счетчик всех пользователей
    blogs_count = Blog.objects.all().count()  # счетчик всех блогов
    all_know = Tematics.objects.all()  # все темы блогов
    populated, last_entrys = popup_and_last()
    context = {
        'title_name': 'О сайте',
        'description': "О сайте",
        'users_count': users_count,
        'blogs_count': blogs_count,
        'all_know': all_know,
        'blogs': blogs,
        'populated': populated,
        'last_entrys': last_entrys

mainapp/templates/base_generic.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>MyBlog New Generic</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

  {% if description%}
  <meta name="description" content="{{ description }}"/>
  {% endif %}

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  
  <!-- Добавление дополнительного статического CSS файла -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">

  <script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
  <script src="{% static '/js/jquery-3.4.1.min.js' %}"></script>
  <script src="{% static '/js/reload_left_bar.js' %}"></script>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
  <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
  {% block javascript %}{% endblock %}


</head>

<body>
<div class="container">
  {# include 'includes/head-navblock.html' #}
</div>
<div class="nav-plase">
    <div class="container">
      {% include 'includes/navblock.html' %}
    </div>
</div>
<div class="content-plase">
  <div class="container content-plase">
      <div class="row no-gutters">
        <div class="col-xl-3">
          {% include 'includes/left-block.html' %}
        </div>
      <div class="col-xl-1">
      </div>
      <div class="col-xl-8">

            {% block content %}
            {% endblock %}

            {% block content2 %}
            {% endblock %}

      </div>
  </div>
</div>
<div class="nav-plase">
  <div class="container">
    {% include 'includes/footerblock.html' %}
  </div>
</div>

  <script src="{% static '/js/reload_comment_flags.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

mainapp/templates/contacts.html
{% extends "base_generic.html" %} 

{% load bootstrap4 %} 

{% block content %}
{% load static %}

<div class="row">


        <div class="col-xl-12 text-center">
            <h1>{{ title_name }}</h1>
        </div>

    <div class="col-xl-12 base_content">
        <div class="content-block">
            <div class="content-small-block">
				<p>Предложения и пожелания направляйте на почту: info@p-board.ru</p>
				<br>
				<p style="text-align: center">@master Москва 2020</p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mainapp/templates/index.html
{% extends "base_generic.html" %} 

{% load bootstrap4 %} 

{% block content %}
{% load static %}


<div class="row">
      <div class="col-xl-12 text-center">
        <h1>{{ set_title }}</h1>
      </div>

    <div class="col-xl-12 base_content">
        <div class="content-block">
            <div class="content-small-block">
            <strong>Поиск блога по названию</strong>
            {#-------------------------------------#}

                 <form method="post">
                       {% csrf_token %}
                       {{ form.as_p }}
                       <input type="submit" value="Найти блог">
                 </form>

            {#-------------------------------------#}
            </div>


        </div>
        <div class="content-block">
            <div class="content-small-block">
                {% if user.is_authenticated %}
                    {% if blogs %}
                        <div class="col-xl-12 text-center">
                            <h4>Мои истории</h4>
                        </div>
                        <ol>
                        {% for blog in blogs %}
                            <a style="text-decoration: none;" href="{% url 'blog_app:blog_detail' blog.pk  %}">
                                <div class="center-link">
                                     <li>


                                    <strong>{{ blog.name }}</strong><br>
                                         <span style="font-size: 11pt">Описание: {{ blog.text  }}</span>




                                    </li>
                                </div>
                            </a>
                        {% endfor %}
                        </ol>
                        <p> <a href="{% url 'blog_app:blog_create' %}">Создать новый блог</a></p>
                    {% else %}
                    <p> Вы пока не создали ни одного блога<br>
                        <a href="{% url 'blog_app:blog_create' %}">Создать мой первый блог</a>
                    </p>

                    {% endif %}

                {% else %}
                    <p> Для создания блога, пожалуйста
                        <a href="{% url 'login' %}?next={{request.path}}"><b>войдите</b></a>
                        или <a href="{% url 'register' %}"><b>зарегистрируйтесь</b></a>

                    </p>
                {% endif %}

            </div>
        </div>
        
        {% if open_blogs %}
        <div class="content-block">

            <div class="content-small-block">
                <div class="col-xl-12 text-center">
                    <h4>Блоги пользователей</h4>
                </div>
                <table style="width: 100%; valign: top">
					<tbody>
					<tr>
						<th style="border-bottom: 2px solid #d5d5d5; padding-left: 10px;">Название</th>
						<th style="border-bottom: 2px solid #d5d5d5; padding-left: 10px;">Автор</th>
                        <th style="border-bottom: 2px solid #d5d5d5; padding-left: 10px;">Тема</th>
					</tr>

                    {% for open_blog in page_obj %}
					<tr>
						<td style=" padding-left: 10px; padding-right: 10px; vertical-align: top; display: table-cell;">
							<a href="{% url 'blog_app:blog_detail' open_blog.pk  %}">{{ open_blog.name }}</a>
						</td>
						<td style="padding-left: 10px; padding-right: 10px; vertical-align: top; display: table-cell;">
							<a href="{% url 'blog_app:by_owner' open_blog.owner.pk  %}"> {{ open_blog.owner }}</a>
						</td>
                        <td style="padding-left: 10px; padding-right: 10px; vertical-align: top; display: table-cell;">
                            <a href="{% url 'blog_app:by_tematics' open_blog.group_kn.pk  %}">{{ open_blog.group_kn }}</a>
						</td>
					</tr>

                    {% endfor %}
                    </tbody>
                </table>
                <br>
                <div class="pagination">
						<span class="step-links">
							{% if page_obj.has_previous %}
								<a href="?page=1">&laquo; Первая</a>
								<a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
							{% endif %}

							<span class="current">
								Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
							</span>

							{% if page_obj.has_next %}
								<a href="?page={{ page_obj.next_page_number }}">Следующая</a>
								<a href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
							{% endif %}
						</span>
					</div>


            </div>

        </div>
        {% endif %}




  </div>

</div>
{% endblock %}

mainapp/templates/messages_letter_succes.html
{% extends "base_generic.html" %} 

{% load bootstrap4 %} 

{% block content %}
{% load static %}

<div class="row">

      <div class="col-xl-12 text-center">
        <h1>Успешно!</h1>
      </div>
    <div class="col-xl-12 base_content">
        <div class="content-block">
            <div class="content-small-block">

				<p>Ваше письмо отправлено!<br>
					Ожидайте ответ на адрес электронной почты указанной при регистрации.<br>
					Спасибо!
				</p>
			</div>
		</div>
   </div>
</div>

{% endblock %}

mainapp/templates/send_message.html
{% extends "base_generic.html" %} 

{% load bootstrap4 %} 

{% block content %}
{% load static %}

<div class="row">

        <div class="col-xl-12 text-center">
            <h1>{{ title_name }}</h1>
        </div>

    <div class="col-xl-12 base_content">
        <div class="content-block">
            <div class="content-small-block">
                <p>В Вашем сообщении <b><i>username</i></b> и <b><i>email</i></b> будет прикреплено автоматически.<br>
                    Ожидайте ответ на адрес электронной почты указанной при регистрации.<br>
                    Спасибо!
                </p>
                <form method="post">
                       {% csrf_token %}
                       {{ send_form.as_p }}
                       <input type="submit" value="Отправить">
                 </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mainapp/templates/site_info.html
{% extends "base_generic.html" %} 

{% load bootstrap4 %} 

{% block content %}
{% load static %}


<div class="row">

</div>

<div class="row">

      <div class="col-xl-12 text-center">
        <h1>{{ title_name }}</h1>
      </div>

    <div class="col-xl-12 base_content">
        <div class="content-block">
            <div class="content-small-block">
                <p>Сайт - пример работы, демонстрация навыков программирования Кумпякова Евгения</p>
				<p>При создании сайта использовались технологии:
				<ul>
					<li>Python3 Django;</li>
					<li>Bootstrap4;</li>
					<li>JavaScript (JQuery);</li>
					<li>Html, css;</li>
				</ul>
				</p>
                <h3 style="text-align: center;">Этапы работ</h3>
                <p>Визуальная часть (фронтэнд):
                <ul>
					<li>Предварительный макет;</li>
					<li>Верстка;</li>
					<li>Адаптация под настольную и мобильную версию;</li>
				</ul>
                </p>
                <p>Серверная часть (бэкэнд):
                <ul>
					<li>Предварительное прототипирование;</li>
					<li>Сборка, релиз проекта;</li>
					<li>Развертывание на сервере;</li>
				</ul>
                </p>
				<p>Сайт носит исключительно демонстрационный характер.</p>

				<p>Предложения и пожелания направляйте на почту: info@p-board.ru</p>
            </div>
        </div>
    </div>
</div>

{% endblock %}