blogapp/urls.py
from django.urls import path, re_path
from .views import *


app_name = 'blog_app'


urlpatterns = [
    path('blog_create/', BlogCreate.as_view(), name='blog_create'),
    path('blog_detail/<int:pk>/', blog_detail, name='blog_detail'),
    path('blog_update/<int:pk>/', BlogUpdate.as_view(), name='blog_update'),
    path('blog_delete/<int:pk>/', BlogDelete.as_view(), name='blog_delete'),

    path('entry_create/<int:pk>/', EntryCreate.as_view(), name='entry_create'),
    path('entry_detail/<int:pk>/', entry_detail, name='entry_detail'),
    path('entry_update/<int:pk>/', EntryUpdate.as_view(), name='entry_update'),

    path('by_tematics/<int:pk>/', BlogByTematicsListView.as_view(), name='by_tematics'),

    path('by_owner/<int:pk>/', BlogByOwnerListView.as_view(), name='by_owner'),

    path('block_entry_create/<int:pk>/', BlockEntryCreate.as_view(), name='block_entry_create'),
    path('block_update/<int:entry_pk>/<int:pk>/', BlockEntryUpdate.as_view(), name='block_update'),
    path('block_delete/<int:entry_pk>/<int:pk>/', BlockDelete.as_view(), name='block_delete'),

]

blogsite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from mainapp.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cabinet/', include('cabinet.urls')),
    url(r'^$', index, name='index'),
    path('main/', include('mainapp.urls')),
    path('blog/', include('blogapp.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from .views import *


app_name = 'mainapp'


urlpatterns = [
    url(r'^$', index, name='index'),
    path('send_message/<int:pk>/', send_message, name='send_message'),

    path('ajax/reload_group/', views.reload_group, name='ajax_reload_group'),  # скролл на странице index

    # панель вверху (раньше была слева)
    path('ajax/reload_data_left_bar/', views.reload_data_left_bar, name='ajax_reload_data_left_bar'),

    # страница комментариев
    path('ajax/reload_comment_block/<int:pk>/', reload_comment_block, name='ajax_reload_comment-block'),

    path('site-info/', site_info, name='site_info'),
    path('contacts/', contacts, name='contacts'),
]

blogapp/models.py
from django.utils.html import mark_safe
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from markdown import markdown

from mainapp.tasks import send_new_comment_notification
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill
from PIL import Image


# Максимальный размер изображения по большей стороне
_MAX_SIZE = 700


class Tematics(models.Model):
    name = models.CharField(max_length=100, verbose_name="Тема блога")
    rating = models.DecimalField(verbose_name='Рейтинг', max_digits=8, decimal_places=0, default=500)

    class Meta:
        verbose_name_plural = "Темы блогов"
        verbose_name = "Тема блога"
        ordering = ['rating']

    def __str__(self):
        return self.name


class Blog(models.Model):
    VISIBLE = (
        ('open', 'Показывать всем'),
        ('close', 'Скрыть'),
    )
    name = models.CharField(max_length=100, verbose_name="Название")
    rating = models.DecimalField(verbose_name='Рейтинг', max_digits=8, decimal_places=0, default=500)
    group_kn = models.ForeignKey(Tematics, on_delete=models.SET_NULL, null=True, verbose_name='Тематика блога')
    created = models.DateTimeField(verbose_name='Создано', auto_now_add=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Автор блога")
    visible = models.CharField(max_length=5, choices=VISIBLE, blank=True, default='close',
                               verbose_name="Настройки видимости", )
    text = models.TextField(verbose_name="Краткое описание блога")
    # slug = models.SlugField(max_length=200, db_index=True, unique=True,  default=None)

    class Meta:
        verbose_name_plural = "Блоги"
        verbose_name = "Блог"
        ordering = ['rating']

    def __str__(self):
        """Возвращает строковое проедставление модели, первые 50 символов"""
        return self.text[:50] + "..."


class Entry(models.Model):
    created = models.DateTimeField(verbose_name='Создано', auto_now_add=True)
    text = models.TextField(verbose_name="Текст сообщение")
    rating = models.DecimalField(verbose_name='Рейтинг', max_digits=8, decimal_places=0, default=500)
    blog_id = models.ForeignKey(Blog, on_delete=models.CASCADE, null=True, verbose_name='Блог')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Автор сообщения")
    count = models.PositiveIntegerField(verbose_name="Просмотры", default=0)
    # slug = models.SlugField(max_length=200, db_index=True, unique=True,  default=None)
    img = ProcessedImageField(upload_to='images',
                              null=True,
                              blank=True,)
    entry_thumbnail = ImageSpecField(source='img',
                                     processors=[ResizeToFill(100, 56)],
                                     format='JPEG',
                                     options={'quality': 60},
                                     )

    def get_text_as_markdown(self):
        return mark_safe(markdown(self.text, safe_mode='escape'))

    def save(self, *args, **kwargs):
        # Сначала - обычное сохранение
        super(Entry, self).save(*args, **kwargs)

        # Проверяем, есть ли изображение?
        if self.img:
            filepath = self.img.path
            width = self.img.width
            height = self.img.height

            max_size = max(width, height)

            # Может, и не надо ничего менять?
            if max_size > _MAX_SIZE:
                # Надо, Федя, надо
                image = Image.open(filepath)
                # resize - безопасная функция, она создаёт новый объект, а не
                # вносит изменения в исходный, поэтому так
                image = image.resize(
                    (round(width / max_size * _MAX_SIZE),  # Сохраняем пропорции
                     round(height / max_size * _MAX_SIZE)),
                    Image.ANTIALIAS
                )
                # И не забыть сохраниться
                image.save(filepath)

    class Meta:
        verbose_name_plural = "Сообщения для блогов"
        verbose_name = "Сообщение для блогов"
        ordering = ['created']

    def __str__(self):
        """Возвращает строковое проедставление модели, первые 50 символов"""
        return self.text[:50] + "..."


class BlockEntry(models.Model):
    entry_id = models.ForeignKey(Entry, on_delete=models.CASCADE, null=True, verbose_name='Запись блога')
    text = models.TextField(null=True, blank=True, verbose_name="Текст блока")
    img = models.ImageField(null=True, blank=True, verbose_name='Изображение', upload_to='images')

    def save(self, *args, **kwargs):
        # Сначала - обычное сохранение
        super(BlockEntry, self).save(*args, **kwargs)
        # Проверяем, есть ли изображение?
        if self.img:
            filepath = self.img.path
            width = self.img.width
            height = self.img.height
            max_size = max(width, height)
            # Может, и не надо ничего менять?
            if max_size > _MAX_SIZE:
                # Надо, Федя, надо
                image = Image.open(filepath)
                # resize - безопасная функция, она создаёт новый объект, а не
                # вносит изменения в исходный, поэтому так
                image = image.resize(
                    (round(width / max_size * _MAX_SIZE),  # Сохраняем пропорции
                     round(height / max_size * _MAX_SIZE)),
                    Image.ANTIALIAS
                )
                # И не забыть сохраниться
                image.save(filepath)

    class Meta:
        verbose_name_plural = "Блоки сообщений для блогов"
        verbose_name = "Блок сообщения для блога"
        # ordering = ['pk']

    def __str__(self):
        """Возвращает строковое проедставление модели, первые 50 символов"""
        return self.text[:50] + "..."


class Comment(models.Model):
    created = models.DateTimeField(verbose_name='Создано', auto_now_add=True)
    text = models.TextField(verbose_name="Текст комментария")
    rating = models.DecimalField(verbose_name='Рейтинг', max_digits=8, decimal_places=0, default=500)
    entry_id = models.ForeignKey(Entry, on_delete=models.CASCADE, null=True, verbose_name='Сообщение')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Автор комментария")
    new = models.BooleanField(default=True, verbose_name='Новый комментарий?')

    class Meta:
        verbose_name_plural = "Комментарии"
        verbose_name = "Комментарии"
        ordering = ['created']

    def __str__(self):
        """Возвращает строковое проедставление модели, первые 50 символов"""
        return self.text[:50] + "..."


def post_save_dispatcher(sender, **kwargs):
    comment_obj = kwargs['instance']
    commnt = comment_obj.text
    author = comment_obj.entry_id.owner  # автор блога
    blog = comment_obj.entry_id.blog_id.name  # название блога
    entry_url = comment_obj.entry_id.pk  # url для entry
    if kwargs['created'] and author.send_messages:
        # send_new_comment_notification(kwargs['instance'])
        send_new_comment_notification.delay(author.pk, blog, entry_url)


post_save.connect(post_save_dispatcher, sender=Comment)


class Answer(models.Model):
    created = models.DateTimeField(verbose_name='Создан', auto_now_add=True)
    text = models.TextField(verbose_name="Текст ответа")
    rating = models.DecimalField(verbose_name='Рейтинг', max_digits=8, decimal_places=0, default=500)
    comment_id = models.CharField(max_length=50, verbose_name='ID_комментария')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Автор ответа")
    new = models.BooleanField(default=True, verbose_name='Новый ответ?')

    class Meta:
        verbose_name_plural = "Ответы"
        verbose_name = "Ответ"
        ordering = ['created']

    def __str__(self):
        """Возвращает строковое проедставление модели, первые 50 символов"""
        return self.text[:50] + "..."

blogapp/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Tematics, Blog, Entry, Comment, Answer, BlockEntry


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('name', 'group_kn', 'visible', 'text')
    """
    def clean_slug(self):
        new_slug = self.changed_data['slug'].lower()

        if new_slug == 'create':
            raise ValidationError('Slug may not be "Create"')
        if Blog.objects.filter(slug__iexact=new_slug).count():
            raise ValidationError('Slug mast be unique')
    """

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ('img', 'text',)
        widgets = {'owner': forms.HiddenInput, 'blog_id': forms.HiddenInput, 'rating': forms.HiddenInput}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', 'owner', 'entry_id')
        widgets = {'owner': forms.HiddenInput, 'entry_id': forms.HiddenInput, 'rating': forms.HiddenInput}


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ('text', 'owner', 'comment_id')
        widgets = {'owner': forms.HiddenInput, 'comment_id': forms.HiddenInput, 'rating': forms.HiddenInput}


class SearchBlog(forms.Form):
    keydata = forms.CharField(label='Введите название, или часть названия')


class BlockEntryForm(forms.ModelForm):
    class Meta:
        model = BlockEntry
        fields = ('img', 'text', 'entry_id')
        # widgets = {'entry_id': forms.HiddenInput, }

blogapp/templates/blog_confirm_delete.html
{% extends "base_generic.html" %}

{% load bootstrap4 %}

{% block content %}
{% load static %}

<div class="row">

      <div class="col-xl-12 text-center">
        <h1>{{ set_title }}</h1>
      </div>

    <div class="col-xl-12 base_content">
        <div class="content-block">
            <div class="content-small-block">

				<p>Уверены?</p>
				<form action="" method="POST">
					  {% csrf_token %}
					  <input type="submit" action="" value="Да, удалить" />
				</form>
            {#-------------------------------------#}
            </div>
        </div>
   </div>
</div>
{% endblock %}

blogapp/templates/blog_detail.html
{% extends "base_generic.html" %} 

{% load bootstrap4 %} 

{% block content %}
{% load static %}

<div class="row">

	 <div class="col-xl-12 text-center">
        <h1>"{{ set_title }}"
			{% if current_user != current_blog.owner %}
			<small>автор: <i>{{ current_blog.owner }}</i></small>
			{% endif %}
		</h1>
      </div>

    <div class="col-xl-12 base_content">
        <div class="content-block">
            <div class="content-small-block">
				<table style="width: 100%; valign: top">
					<tbody>
					<tr>
						<th style="border-bottom: 2px solid #d5d5d5; padding-left: 10px;">Наименование</th>
						<th style="border-bottom: 2px solid #d5d5d5; padding-left: 10px;">Значение</th>
					</tr>
					<tr>
						<td style=" padding-left: 10px; padding-right: 10px; vertical-align: top; display: table-cell;">
							Тематика блога<br>
						</td>
						<td style="padding-left: 10px; padding-right: 10px; vertical-align: top; display: table-cell;">
							{{ current_blog.group_kn }}<br>
						</td>
					</tr>
					<tr>
						<td style="padding-left: 10px; padding-right: 10px; vertical-align: top; display: table-cell;">
							Создан<br>
						</td>
						<td style=" padding-left: 10px; padding-right: 10px; vertical-align: top; display: table-cell;">
							{{ current_blog.created }}<br>
						</td>
					</tr>
					{% if current_user == current_blog.owner %}
					<tr>
						<td style=" padding-left: 10px; padding-right: 10px; vertical-align: top; display: table-cell;">
							Видимость<br>
						</td>
						<td style=" padding-left: 10px; padding-right: 10px; vertical-align: top; display: table-cell;">
							<span
							{% if current_blog.visible == 'close' %}
								style="color: red; font-weight: bold;"
							{% else %}
								style="color: #58a8fd; font-weight: bold;"
							{% endif %}
							>
								{{ current_blog.get_visible_display }}
							</span>
						</td>
					</tr>
					{% endif %}
					<tr>
						<td style=" padding-left: 10px; padding-right: 10px; vertical-align: top; display: table-cell;">
							Краткое описание<br>
						</td>
						<td style=" padding-left: 10px; padding-right: 10px; vertical-align: top; display: table-cell;">
							{{ current_blog.text }}<br>
						</td>
					</tr>

					</tbody>
				</table>
				<br>
				{% if current_user == current_blog.owner %}
					<a href="{% url 'blog_app:blog_update' current_blog.pk %}">Изменить данные блога</a>
					<br>
					<a href="{% url 'blog_app:entry_create' current_blog.pk %}">Добавить сообщение</a>
					<br>
					<a style="color: red" href="{% url 'blog_app:blog_delete' current_blog.pk %}">Удалить блог</a>
				{% endif %}

            {#-------------------------------------#}

			<div>
				{% if current_entrys %}

					{% for entry in page_obj %}

						<a href="{% url 'blog_app:entry_detail' entry.pk  %}" style="text-decoration: none;">
							<div class="item-entry">

								<div class="entry-thumb-image">
									<img class="small-entry-thumb-image" src="{{ entry.entry_thumbnail.url }}" alt="Entry-{{ current_entry.pk }} image">
								</div>
								<div class="entry-description">
									{{ entry.created }}	<br>
									{{ entry }}
								</div>

								<div class="comment">
									Комментариев:
									{% for item in arr %}
										{% if entry.pk == item.pk %}
											{{ item.value }}
											{% if item.new_comments != 0 %}
												{% if context.owner %}
												<span style="color: red">(+{{ item.new_comments }})</span>
												{% endif %}
											{% endif %}

										{% endif %}
									{% endfor %}

								</div>
							</div>
						</a>
					{% endfor %}
					<div class="pagination">
						<span class="step-links">
							{% if page_obj.has_previous %}
								<a href="?page=1">&laquo; Первая</a>
								<a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
							{% endif %}

							<span class="current">
								Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
							</span>

							{% if page_obj.has_next %}
								<a href="?page={{ page_obj.next_page_number }}">Следующая</a>
								<a href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
							{% endif %}
						</span>
					</div>

				{% else %}
				<br>
				<b>Сообщений в этом блоге еще нет :(</b>
				{% endif %}
				<br>

			</div>

			{% if current_user == current_blog.owner %}
				<a href="{% url 'blog_app:entry_create' current_blog.pk %}">Добавить сообщение</a>
			{% endif %}
			{% if not user.is_authenticated %}
				<p>Комментировать могут только зарегистирированные пользователи</p>
				<a href="{% url 'login' %}?next={{request.path}}">Войдите</a><br>
				<a href="{% url 'register' %}">Или зарегистрируйтесь</a>
			{% endif %}

            {#-------------------------------------#}

        </div>



   </div>

  </div>

</div>

{% endblock %}

blogapp/templates/blog_list.html
{% extends "base_generic.html" %} 

{% load bootstrap4 %} 

{% block content %}
{% load static %}

<div class="row">

	   <div class="col-xl-12 text-center">
        <h1>Фильтр по теме: "{{ current_tematics.name }}"</h1>
      </div>

    <div class="col-xl-12 base_content">
        <div class="content-block">
            <div class="content-small-block">
				 <table style="width: 100%; valign: top">
					<tbody>
					<tr>
						<th style="border-bottom: 2px solid #d5d5d5; padding-left: 10px;">Название</th>
						<th style="border-bottom: 2px solid #d5d5d5; padding-left: 10px;">Автор</th>
                        <th style="border-bottom: 2px solid #d5d5d5; padding-left: 10px;">Тема</th>
					</tr>
					{% if blog_list %}
						{% for blog in blog_list %}
						<tr>
							<td style=" padding-left: 10px; padding-right: 10px; vertical-align: top; display: table-cell;">
								<a href="{% url 'blog_app:blog_detail' blog.pk  %}">{{ blog.name }}</a>
							</td>
							<td style="padding-left: 10px; padding-right: 10px; vertical-align: top; display: table-cell;">
								<a href="{% url 'blog_app:by_owner' blog.owner.pk  %}"> {{ blog.owner }}</a>
							</td>
							<td style="padding-left: 10px; padding-right: 10px; vertical-align: top; display: table-cell;">
								 {{ blog.group_kn }}
							</td>
						</tr>
						{% endfor %}





					{% else %}
						<tr>
							<td style=" padding-left: 10px; padding-right: 10px; vertical-align: top; display: table-cell;">
								Ничего не найдено
							</td>
							<td style="padding-left: 10px; padding-right: 10px; vertical-align: top; display: table-cell;">
								-
							</td>
							<td style="padding-left: 10px; padding-right: 10px; vertical-align: top; display: table-cell;">
								-
							</td>
						</tr>
					{% endif %}
                    </tbody>
                </table>
				<br>
				<div class="pagination">
					<span class="step-links">
						{% if page_obj.has_previous %}
							<a href="?page=1">&laquo; Первая</a>
							<a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
						{% endif %}

						<span class="current">
							Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
						</span>

						{% if page_obj.has_next %}
							<a href="?page={{ page_obj.next_page_number }}">Следующая</a>
							<a href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
						{% endif %}
					</span>
				</div>

			</div>
		</div>



   </div>

  </div>


{% endblock %}

blogapp/templates/blog_list_by_owner.html
{% extends "base_generic.html" %} 

{% load bootstrap4 %} 

{% block content %}
{% load static %}

<div class="row">

	  <div class="col-xl-12 text-center">
        <h1>Фильтр по автору: "{{ current_owner.username }}"</h1>
      </div>

    <div class="col-xl-12 base_content">
        <div class="content-block">
            <div class="content-small-block">
				 <table style="width: 100%; valign: top">
					<tbody>
					<tr>
						<th style="border-bottom: 2px solid #d5d5d5; padding-left: 10px;">Название</th>
						<th style="border-bottom: 2px solid #d5d5d5; padding-left: 10px;">Автор</th>
                        <th style="border-bottom: 2px solid #d5d5d5; padding-left: 10px;">Тема</th>
					</tr>
					{% if blog_list %}
						{% for blog in blog_list %}
						<tr>
							<td style=" padding-left: 10px; padding-right: 10px; vertical-align: top; display: table-cell;">
								<a href="{% url 'blog_app:blog_detail' blog.pk  %}">{{ blog.name }}</a>
							</td>
							<td style="padding-left: 10px; padding-right: 10px; vertical-align: top; display: table-cell;">
								{{ blog.owner }}
							</td>
							<td style="padding-left: 10px; padding-right: 10px; vertical-align: top; display: table-cell;">
								<a href="{% url 'blog_app:by_tematics' blog.group_kn.pk  %}">{{ blog.group_kn }}</a>
							</td>
						</tr>
						{% endfor %}





					{% else %}
						<tr>
							<td style=" padding-left: 10px; padding-right: 10px; vertical-align: top; display: table-cell;">
								Ничего не найдено
							</td>
							<td style="padding-left: 10px; padding-right: 10px; vertical-align: top; display: table-cell;">
								-
							</td>
							<td style="padding-left: 10px; padding-right: 10px; vertical-align: top; display: table-cell;">
								-
							</td>
						</tr>
					{% endif %}
                    </tbody>
                </table>
				<br>
				<div class="pagination">
					<span class="step-links">
						{% if page_obj.has_previous %}
							<a href="?page=1">&laquo; Первая</a>
							<a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
						{% endif %}

						<span class="current">
							Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
						</span>

						{% if page_obj.has_next %}
							<a href="?page={{ page_obj.next_page_number }}">Следующая</a>
							<a href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
						{% endif %}
					</span>
				</div>

			</div>
		</div>



   </div>

  </div>
{% endblock %}

blogapp/templates/create_block_entry.html
{% extends "base_generic.html" %} 

{% load bootstrap4 %} 

{% block content %}
{% load static %}

<div class="row">

      <div class="col-xl-12 text-center">
        <h1>{{ set_title }}</h1>
      </div>

    <div class="col-xl-12 base_content">
        <div class="content-block">
            <div class="content-small-block">

            {#-------------------------------------#}
              <form method="post" enctype="multipart/form-data">
					{% csrf_token %}
					<table>
						{{ form.as_p }}
					</table>

					<input type="submit" value="Добавить">
				</form>
            {#-------------------------------------#}
            </div>
        </div>
   </div>

</div>
{% endblock %}

blogapp/templates/entry_create_succes.html
{% extends "base_generic.html" %}

{% load bootstrap4 %}

{% block content %}
{% load static %}

<div class="row">

      <div class="col-xl-12 text-center">
        <h1>{{ set_title }}</h1>
      </div>

    <div class="col-xl-12 base_content">
        <div class="content-block">
            <div class="content-small-block">
					<h1 style="text-align: center">Успешно!</h1>
				<p>
					Сообщение добавлено!
				</p>
            {#-------------------------------------#}
            </div>


        </div>



   </div>

  </div>
{% endblock %}

blogapp/templates/entry_detail.html
{% extends "base_generic.html" %} 

{% load bootstrap4 %} 

{% block content %}
{% load static %}

<div class="row">

      <div class="col-xl-12 text-center">
        <h1>{{ set_title }}
            {% if current_user != current_entry.owner %}
			<small>автор: <i>{{ current_entry.owner }}</i></small>
			{% endif %}
        </h1>
      </div>

    <div class="col-xl-12 base_content">
        <div class="content-block">
            <div class="content-small-block">
				<strong>Сообщение от {{ current_entry.created }}:</strong>
                <p><small>Просмотров: {{ current_entry.count }}</small></p>
                <div class="entry-block">
                    {% if current_entry.img %}
                        <div class="entry-image">
                            <img src="{{ current_entry.img.url }}" alt="Entry-{{ current_entry.pk }} image">
                        </div>
                        <br>
                    {% endif %}

				    {# current_entry.text|linebreaks #}
                    {{ current_entry.get_text_as_markdown }}

                    {% if user.is_authenticated %}
                        {% if owner %}
                        <div class="edit-block">
                            <span><a href="{% url 'blog_app:entry_update' current_entry.pk %}">
                                <img class="img-fluid" src="{% static 'images/edit_button.png' %}" alt="Edit image">
                            </a></span>
                            <span><a href="{# url 'blog_app:block_update' current_entry.pk item_block.pk #}">
                                <img class="img-fluid" src="{% static 'images/delete_button.png' %}" alt="Edit image">
                            </a></span>
                        </div>
                        {% endif %}
                    {% endif %}
                </div>

                {% if all_block %}
                    {% for item_block in all_block %}
                    <div class="entry-block">
                        <div class="entry-image">
                            <img src="{{ item_block.img.url }}" alt="BlockEntry-{{ item_block.pk }} image">
                        </div>
                        <br>
                        {{ item_block.text|linebreaks }}
                        {% if user.is_authenticated %}
                            {% if owner %}
                            <div class="edit-block">
                                <span><a href="{% url 'blog_app:block_update' current_entry.pk item_block.pk %}">
                                    <img class="img-fluid" src="{% static 'images/edit_button.png' %}" alt="Edit image">
                                </a></span>
                                <span><a href="{% url 'blog_app:block_delete' current_entry.pk item_block.pk %}">
                                    <img class="img-fluid" src="{% static 'images/delete_button.png' %}" alt="Edit image">
                                </a></span>
                            </div>
                            {% endif %}
                        {% endif %}
                    </div>
                    {% endfor %}
                {% endif %}

                {% if user.is_authenticated %}
                    {% if owner %}
                    <div class="add-block">
                        <div class="edit-block-add">
                            <a href="{% url 'blog_app:block_entry_create' current_entry.pk %}">
                                <img class="img-fluid" src="{% static 'images/add_button.png' %}" alt="Edit image">
                            </a>
                        </div>
                    </div>
                    {% endif %}
                {% endif %}
                <br>
                <br>
                <div class="comment-block" id="CommentBlock"
                     comment-block-url="{% url 'mainapp:ajax_reload_comment-block' current_entry.pk %}">

                </div>
                {% if user.is_authenticated %}

                <div class="border-text" style="height: 5px;width: 100%;"></div>

                    <div class="collapse multi-collapse" id="collapse">
                        {% if owner %}
                        <p>Ответ на комментарий: "<span id="messagess_b">empty</span>"</p>
                        {% endif %}
                        <b>{{ user.username }}:</b><br>
                        <div class="comment-text-block" id="CommentText">
                            {#-------------------------------------#}
                              <form method="post">
                                    {% csrf_token %}
                                    <table>
                                        {{ form.as_p }}
                                    </table>

                                    <input type="submit" value="Добавить">
                                </form>
                            {#-------------------------------------#}
                        </div>
                    </div>
                </div>
                {% endif %}
           </div>
        </div>
   </div>

  </div>

{% block js %}
    <script src="{% static '/js/reload_comment-block.js' %}"></script>
    <script src="{% static '/js/answer_block.js' %}"></script>
{% endblock %}
{% endblock %}