blogapp/urls.py
from django.urls import path, re_path
from .views import *


app_name = 'blog_app'


urlpatterns = [
    path('blog_create/', BlogCreate.as_view(), name='blog_create'),
    path('blog_detail/<int:pk>/', blog_detail, name='blog_detail'),
    path('blog_update/<int:pk>/', BlogUpdate.as_view(), name='blog_update'),
    path('blog_delete/<int:pk>/', BlogDelete.as_view(), name='blog_delete'),

    path('entry_create/<int:pk>/', EntryCreate.as_view(), name='entry_create'),
    path('entry_detail/<int:pk>/', entry_detail, name='entry_detail'),
    path('entry_update/<int:pk>/', EntryUpdate.as_view(), name='entry_update'),

    path('by_tematics/<int:pk>/', BlogByTematicsListView.as_view(), name='by_tematics'),

    path('by_owner/<int:pk>/', BlogByOwnerListView.as_view(), name='by_owner'),

    path('block_entry_create/<int:pk>/', BlockEntryCreate.as_view(), name='block_entry_create'),
    path('block_update/<int:entry_pk>/<int:pk>/', BlockEntryUpdate.as_view(), name='block_update'),
    path('block_delete/<int:entry_pk>/<int:pk>/', BlockDelete.as_view(), name='block_delete'),

]

blogsite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from mainapp.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cabinet/', include('cabinet.urls')),
    url(r'^$', index, name='index'),
    path('main/', include('mainapp.urls')),
    path('blog/', include('blogapp.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from .views import *


app_name = 'mainapp'


urlpatterns = [
    url(r'^$', index, name='index'),
    path('send_message/<int:pk>/', send_message, name='send_message'),

    path('ajax/reload_group/', views.reload_group, name='ajax_reload_group'),  # скролл на странице index

    # панель вверху (раньше была слева)
    path('ajax/reload_data_left_bar/', views.reload_data_left_bar, name='ajax_reload_data_left_bar'),

    # страница комментариев
    path('ajax/reload_comment_block/<int:pk>/', reload_comment_block, name='ajax_reload_comment-block'),

    path('site-info/', site_info, name='site_info'),
    path('contacts/', contacts, name='contacts'),
]

mainapp/models.py
from django.db import models

# Create your models here.

mainapp/forms.py
from django import forms


class SendMessage(forms.Form):
    text_data = forms.CharField(label='Сообщение', widget=forms.Textarea)

mainapp/views.py
from django.shortcuts import render
from blogapp.forms import SearchBlog
from blogapp.models import Tematics, Blog, Entry, Comment, Answer
from cabinet.models import AdvUser
from django.core.paginator import Paginator
from .forms import SendMessage
from django.template.loader import render_to_string


def popup_and_last():
    populated = []
    arr_populated = Entry.objects.all().order_by('-count')
    count_pop = len(arr_populated)
    if count_pop <= 10:
        count_pop_max = count_pop
    else:
        count_pop_max = 10
    for i in range(count_pop_max):
        populated.append(arr_populated[i])

    last_entrys = []
    arr_populated = Entry.objects.all().order_by('-created')
    count_pop = len(arr_populated)
    if count_pop <= 10:
        count_pop_max = count_pop
    else:
        count_pop_max = 10
    for i in range(count_pop_max):
        last_entrys.append(arr_populated[i])

    return populated, last_entrys


def index(request, pk=None):
    title_name = 'Мой блог'
    description = "Мой блог: создай свой блог, делись мыслями и интересными историями."
    visible_blogs = Blog.objects.filter(visible='open').order_by('name')

    users_count = AdvUser.objects.all().count()  # счетчик всех пользователей
    blogs_count = Blog.objects.all().count()  # счетчик всех блогов
    all_know = Tematics.objects.all()  # все темы блогов

    paginator = Paginator(visible_blogs, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    populated, last_entrys = popup_and_last()

    arr = []
    if request.user.is_authenticated:
        blogs = Blog.objects.filter(owner=request.user).order_by('name')
        entrys = Entry.objects.filter(blog_id=pk).count()
        """ Ниже формируем массив для вывода вспомогательных данных в шаблон,
                поскольку требуется вывод сложных структур
            """

        for item_blog in blogs:
            count_entrys = Entry.objects.filter(blog_id=item_blog.pk).count()   # считаем количество сообщений блога
            item_value = {
                'pk': item_blog.pk,  # делаем привязку к блогу
                'value': count_entrys   # указываем количество сообщений блога
            }
            arr.append(item_value)
    else:
        blogs = []

    if request.method == 'POST':
        form = SearchBlog(request.POST)
        if form.is_valid():
            keydata = form.cleaned_data['keydata']
            current_blogs = Blog.objects.filter(name__icontains=keydata).order_by('name')

            paginator = Paginator(current_blogs, 10)
            page_number = request.GET.get('page')
            page_obj = paginator.get_page(page_number)

            context = {'page_obj': page_obj,
                       'users_count': users_count,
                       'blogs_count': blogs_count,
                       'all_know': all_know,
                       'keydata': keydata,
                       'serch_word': keydata
                       }
            return render(request, 'search_blog.html', context)
        else:
            context = {'form': form, }
            return render(request, 'index.html', context)
    else:
        form = SearchBlog()

        context = {'set_title': title_name,
                   'description': description,
                   'form': form,
                   'blogs': blogs,
                   'open_blogs': visible_blogs,
                   'arr': arr,   # передаем свои дополнительные данные
                   'page_obj': page_obj,
                   'users_count': users_count,
                   'blogs_count': blogs_count,
                   'all_know': all_know,
                   'populated': populated,
                   'last_entrys': last_entrys
                   }
        return render(request, 'index.html', context)


def reload_group(request):
    area_id = request.GET.get('id_area')
    current_group = Tematics.objects.filter(area_kn=area_id).order_by('name')
    return render(request, 'inc_templates_misc/group_dropdown_list_options.html', {'group_kn': current_group})


def reload_data_left_bar(request):
    """Здесь динамически выводим актуальные данные на странице в блок слева, обновляем 1 раз в 5 сек"""
    users_count =AdvUser.objects.all().count()     # счетчик всех пользователей
    blogs_count = Blog.objects.all().count()     # счетчик всех блогов
    all_know = Tematics.objects.all()     # все темы блогов
    comment_flag = False
    if request.user.is_authenticated:
        blogs = Blog.objects.filter(owner=request.user).order_by('name')
        arr = []
        for item_blog in blogs:
            # считаем количество сообщений блога
            count_entrys = Entry.objects.filter(blog_id=item_blog.pk).count()

            # считаем количество новых комментариев
            new_comments = Comment.objects.filter(entry_id__blog_id=item_blog.pk, new=True).count()
            if new_comments:
                comment_flag = True
            item_value = {
                'pk': item_blog.pk,  # делаем привязку к блогу
                'value': count_entrys,   # указываем количество сообщений блога
                'new_comments': new_comments,
                'visible': item_blog.visible,
            }
            arr.append(item_value)
        context = {
            'is_authenticated': True,
            'username': request.user.username,
            'blogs_count': blogs_count,
            'users_count': users_count,
            'users_blogs': Blog.objects.filter(owner=request.user).count(),
            'blogs': blogs,
            'arr': arr,
            'all_know': all_know,
            'comment_flag': comment_flag
        }
    else:
        context = {
            'is_authenticated': False,
            'blogs_count': blogs_count,
            'users_count': users_count,
            'all_know': all_know,
        }

    return render(request, 'inc_templates_misc/reload_data_left_bar.html', {'context': context})


def reload_comment_block(request, pk):
    current_comments = Comment.objects.filter(entry_id=pk).order_by('created')
    current_user = request.user
    current_entry = Entry.objects.get(pk=pk)    # получили сообщение
    current_comments_count = current_comments.count()
    array = []  # пустой массив для данных

    for comment in current_comments:
        current_item_answer = Answer.objects.filter(comment_id=comment.pk)
        item_value = {
            'pk': comment.pk,
            'value': current_item_answer
        }
        array.append(item_value)

    owner_entry = current_entry.owner
    if current_user == owner_entry:
        # обнуляем признак "new" только если смотрит хозяин сообщения
        show_new = True
        owner = True
        new_comments = Comment.objects.filter(entry_id=pk, new=True,).order_by('created')
        if new_comments:
            first_comment = new_comments[0]
            first_comment.new = False
            first_comment.save()

    else:
        show_new = False
        owner = False

    context = {
        'current_comments': current_comments,
        'current_comments_count': current_comments_count,
        'show_new': show_new,
        'owner': owner,     # хозяин / гость блога
        'array': array,
    }
    return render(request, 'inc_templates_misc/reload_comment_block.html', {'context': context})


def send_message(request, pk):
    users_count = AdvUser.objects.all().count()  # счетчик всех пользователей
    blogs_count = Blog.objects.all().count()  # счетчик всех блогов
    all_know = Tematics.objects.all()  # все темы блогов
    populated, last_entrys = popup_and_last()

    if request.method == 'POST':
        send_form = SendMessage(request.POST)
        if send_form.is_valid():
            text_data = send_form.cleaned_data['text_data']
            author = AdvUser.objects.get(pk=pk)

            moderators = AdvUser.objects.filter(is_staff=True)
            for moderator in moderators:
                context = {'moderator': moderator, 'text_data': text_data, 'author': author}
                subject = render_to_string('email/new_messages_letter.txt', context)
                body_text = render_to_string('email/new_messages_body.txt', context)
                moderator.email_user(subject, body_text)
            context = {
                'title_name': 'Создание сообщения',
                'description': "Создание сообщения",
                'send_form': send_form,
                'users_count': users_count,
                'blogs_count': blogs_count,
                'all_know': all_know,
                'populated': populated,
                'last_entrys': last_entrys
            }
            return render(request, 'messages_letter_succes.html', context)
        else:
            context = {'send_form': send_form, }
            return render(request, 'index.html', context)

    else:
        send_form = SendMessage()
        context = {
            'title_name': 'Создание сообщения',
            'description': "Создание сообщения",
            'send_form': send_form,
            'users_count': users_count,
            'blogs_count': blogs_count,
            'all_know': all_know,
            'populated': populated,
            'last_entrys': last_entrys
        }
        return render(request, 'send_message.html', context)


def site_info(request):
    if request.user.is_authenticated:
        blogs = Blog.objects.filter(owner=request.user).order_by('name')
    else:
        blogs = []

    users_count = AdvUser.objects.all().count()  # счетчик всех пользователей
    blogs_count = Blog.objects.all().count()  # счетчик всех блогов
    all_know = Tematics.objects.all()  # все темы блогов
    populated, last_entrys = popup_and_last()
    context = {
        'title_name': 'О сайте',
        'description': "О сайте",
        'users_count': users_count,
        'blogs_count': blogs_count,
        'all_know': all_know,
        'blogs': blogs,
        'populated': populated,
        'last_entrys': last_entrys

mainapp/templates/includes/footerblock.html
<div class="navbar navbar-light">
    <div class="container">
        <span class="navbar-link">© 2020 Copyright: master</span>
    </div>
</div>

mainapp/templates/includes/group-nav-block.html
<li> <a href="{% url 'mainapp:product_list' %}"
	{% if not request.resolver_match.kwargs.pk %}
		{#class="list-group-item list-group-item-action list-group-item-primary active">#}
		class="button-category button-category-active">
	{% else %}
		{#class="list-group-item list-group-item-action list-group-item-primary">#}
		class="button-category">
	{% endif %}
	Любая
	</a>
</li>
{% for category in categorys %}
	<li>
        <a href="{% url 'mainapp:page_choice_category' modyfy_auto.pk category.pk %}"
        {% if request.resolver_match.kwargs.pk == category.pk %}
                class="button-category button-category-active">
            {% else %}
                class="button-category">
            {% endif %}
        {{ category.name }}
        </a>
	</li>
{% endfor %}

mainapp/templates/includes/head-navblock.html
{% load static %}
<div class="container-fluid header">
  <div class="logo">
    <a href="{% url 'index' %}"><img src="{% static "images/logo.png" %}" >My Blog</a>
  </div>
  <div class="right-flag">
    <div id="comment-res2" class="is-comment" style="display: none"><img src="{% static "images/comment.png" %}" ></div>
  </div>
  <!--div class="contact">
    Написать письмо
  </div-->
</div>

mainapp/templates/includes/left-block.html
<div class="left-nav-block">
    {% if user.is_staff %}
        <div class="widget-title"><h2>На сайте</h2></div>
        <span>Всего блогов: {{ blogs_count }}</span><br>
        <span>Пользователей: {{ users_count }}</span>
    {% endif %}
    <br>

    {% if user.is_authenticated %}
        {% if blogs %}
        <div class="widget-title"><h2>Мои записи</h2></div>
        <ul>
            {% for my_story in blogs %}
                <li><a href="{% url 'blog_app:blog_detail' my_story.pk  %}">{{ my_story.name }}</a>

                </li>
            {% endfor %}
        </ul>
        <br>
        {% endif %}
    {% endif %}

    <div class="widget-title"><h2>Темы блогов</h2></div>
    <ul>
        {% for know in all_know %}
            <li><a href="{% url 'blog_app:by_tematics' know.pk  %}">{{ know.name }}</a>

            </li>
        {% endfor %}
    </ul>
    <div class="widget-title"><h2>Последние записи</h2></div>

    {% if last_entrys %}
        <ul>
        {% for item in last_entrys %}
            <li><a href="{% url 'blog_app:entry_detail' item.pk %}">{{ item }}</a></li>
        {% endfor%}
        </ul>
    {% else %}
        Не найдено
    {% endif %}

    <div class="widget-title"><h2>Популярное</h2></div>
    {% if populated %}
        <ul>
        {% for item in populated %}
            <li><a href="{% url 'blog_app:entry_detail' item.pk %}">{{ item }}</a></li>
        {% endfor%}
        </ul>
    {% else %}
        Не найдено
    {% endif %}
</div>

mainapp/templates/includes/navblock.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-home" href="{% url 'index' %}">Главная</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="container-fluid">
      <div class="navbar-header">

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle header-nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="navbar-link">Темы блогов</span>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% for know in all_know %}
                  <a class="dropdown-item" href="{% url 'blog_app:by_tematics' know.pk  %}">{{ know.name }}</a>
                {% endfor %}

                {% if user.is_staff %}
                <!--a class="dropdown-item" href="">Добавить тему блога</a-->
                {% endif %}
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'mainapp:site_info' %}"><span class="navbar-link">О сайте</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'mainapp:contacts' %}"><span class="navbar-link">Контакты</span></a>

            </li>




            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle header-nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="navbar-link">
                {% if user.is_authenticated %}
                Вы зашли как: {{ user.get_username }}
                {% else %}
                Профиль
                {% endif %}
                </span>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% if user.is_authenticated %}
                  <a class="dropdown-item" href="{% url 'profile' %}">Профиль пользователя</a>
                  <a class="dropdown-item" href="{% url 'profile_change' %}">Изменить личные данные</a>
                  <a class="dropdown-item" href="{% url 'password_change' %}">Изменить пароль</a>
                  <a class="dropdown-item" href="{% url 'profile_delete' %}">Удалить профиль</a>
                  <a class="dropdown-item" href="{% url 'logout' %}?next={{request.path}}">Выйти</a>
                  <a class="dropdown-item" href="{% url 'mainapp:send_message' request.user.pk %}">Написать модератору</a>

                  <!--div class="dropdown-divider"></div-->

                {% else %}
                  <a class="dropdown-item" href="{% url 'login' %}?next={{request.path}}">Войти</a>
                  <a class="dropdown-item" href="{% url 'register' %}">Регистрация</a>
                {% endif %}


              </div>
            </li>
            <li class="nav-item dropdown">
              {% if user.is_authenticated %}
              <div id="comment-res" class="is-comment2" style="display: none"><img src="{% static "images/comment.png" %}" ></div>

              <a class="nav-link dropdown-toggle header-nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="navbar-link">Мои блоги</span>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <div class="reload-pers-menu" id="LeftBlock" data-left-url="{% url 'mainapp:ajax_reload_data_left_bar' %}">

                </div>

              </div>
              {% endif %}
            </li>
          </ul>

        </div>
      </div>
    </div>    
  </nav>

mainapp/templates/includes/product-list.html
{% load static %}
{% if current_product_list %}

<div class="row no-gutters" style="text-align: center">
    <div class="col-3">
        <strong>Фото</strong>
    </div>
    <div class="col-3">
        <strong>Наимен-ние</strong>
    </div>
    <div class="col-3">
        <strong>Цена</strong>
    </div>
    <div class="col-3">
        <strong></strong>
    </div>

</div>

    {% for product in current_product_list %}
<div class="row" style="text-align: center; margin-top: 5px;">
        <div class="col-3">
            {% if product.image %}
            <a href="{% url 'mainapp:product_detail' product.pk %}"><img class="img-fluid basket-img" src="{{ product.image.url }}" alt="Responsive image" style="width: 100px;"></a>
            {% else %}
            Нет фото
            {% endif %}
        </div>
        <div class="col-3">
            <a href="{% url 'mainapp:product_detail' product.pk %}">{{ product.name }}</a></td>
        </div>
        <div class="col-3">
            {{ product.price }}
        </div>
        <div class="col-3 button-more">

        <a class="" data-toggle="collapse" href="#collapse-{{ product.pk }}" role="button" aria-expanded="false" aria-controls="collapse-{{ product.pk }}">Больше</a>

        </div>
</div>

<div class="collapse multi-collapse" id="collapse-{{ product.pk }}">
        <div class="row">
            <div class="col-12">
             <div class="slide-more-block">
                  <div> <!--class="card card-body"-->
                    Описание: {{ product.description  }}
                  </div>
            </div>
      </div>
    </div>
</div>


    {% endfor %}

{% else %}
	Ничего не найдено
{% endif %}